//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramCloneMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryUpload
    {
        public int StoryId { get; set; }
        public string StoryImage { get; set; }
        public Nullable<System.DateTime> StoryDate { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
